config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :countries, except: [:show]
    resources :currencies, except: [:show]

    get "/dashboard", to: "admin#dashboard"
  end

  get "login", to: redirect("/auth/google_oauth2"), as: "login"
  delete "logout", to: "sessions#destroy", as: "logout"
  get "auth/:provider/callback", to: "sessions#create"
  get "auth/failure", to: redirect("/")
  root "home#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/country.rb
class Country < ApplicationRecord
  default_scope { order(name: :asc) }

  before_save { self.code = code.to_s.squish.upcase }

  validates :name, presence: true, length: { maximum: 255 }, uniqueness: { case_sensitive: false }
  validates :code, presence: true, length: { is: 2 }, uniqueness: { case_sensitive: false }
  validates :active, inclusion: { in: [true, false] }

  scope :active, -> { where(active: true) }
end

app/models/currency.rb
class Currency < ApplicationRecord
	default_scope { order(name: :asc) }

  before_save { self.code = code.to_s.squish.upcase }

  validates :name, presence: true, length: { maximum: 255 }, uniqueness: { case_sensitive: false }
	validates :code, presence: true, uniqueness: { case_sensitive: false }
	validates :symbol, presence: true, length: { is: 1 }, uniqueness: { case_sensitive: false }
  validates :active, inclusion: { in: [true, false] }

  scope :active, -> { where(active: true) }
end

app/models/user.rb
class User < ApplicationRecord
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i.freeze

  before_save { self.email = email.downcase }

  validates :email, presence: true, uniqueness: { case_sensitive: false }, format: { with: VALID_EMAIL_REGEX }
  validates :first_name, length: { maximum: 255 }
  validates :last_name, length: { maximum: 255 }

  def self.find_from_auth_hash(auth)
    where(email: auth.info.email).first
  end

  def update_user(auth)
    self.provider = auth.provider
    self.uid = auth.uid
    self.first_name = auth.info.first_name
    self.last_name = auth.info.last_name
  end
end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < ApplicationController
  before_action :authenticate_user, :authenticate_admin_user

  def dashboard; end
end

app/controllers/admin/countries_controller.rb
class Admin::CountriesController < Admin::AdminController
  before_action :find_country, only: [:edit, :update, :destroy]

  def index
    @pagy, @countries = pagy(Country.all, items: 20)
  end

  def new
    @country = Country.new
  end

  def create
    @country = Country.new(country_params)

    if @country.save
      redirect_to admin_countries_path, flash: { success: "Country has been successfully created." }
    else
      render "new"
    end
  end

  def edit; end

  def update
    if @country.update(country_params)
      redirect_to admin_countries_path, flash: { success: "Country has been successfully updated." }
    else
      render "edit"
    end
  end

  def destroy
    @country.destroy
    flash[:danger] = "Country has been successfully deleted."
    redirect_to admin_countries_path
  end

  private

  def country_params
    params.require(:country).permit(:name, :code, :active)
  end

  def find_country
    @country = Country.find(params[:id])
  end
end

app/controllers/admin/currencies_controller.rb
class Admin::CurrenciesController < ApplicationController
    before_action :find_currency, only: [:edit, :update, :destroy]

  def index
    @pagy, @currencies = pagy(Currency.all, items: 20)
  end

  def new
    @currency = Currency.new
  end

  def create
    @currency = Currency.new(currency_params)

    if @currency.save
      redirect_to admin_currencies_path, flash: { success: "Currency has been successfully created." }
    else
      render "new"
    end
  end

  def edit; end

  def update
    if @currency.update(currency_params)
      redirect_to admin_currencies_path, flash: { success: "Currency has been successfully updated." }
    else
      render "edit"
    end
  end

  def destroy
    @currency.destroy
    flash[:danger] = "Currency has been successfully deleted."
    redirect_to admin_currencies_path
  end

  private

  def currency_params
    params.require(:currency).permit(:name, :code, :symbol, :active)
  end

  def find_currency
    @currency = Currency.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
  protect_from_forgery with: :exception
  helper_method :current_user

  def authenticate_user
    redirect_to login_path unless current_user
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def authenticate_admin_user
    authenticate_user
    return unless current_user

    redirect_to root_path, flash: { danger: "Need to have admin access" } unless current_user.admin
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :find_user, only: [:create]

  def create
    unless @user
      flash[:danger] = "You are not authorized user."
      redirect_to root_path
      return
    end

    @user.update_user(request.env["omniauth.auth"])

    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "You have successfully signed in."
    else
      flash[:danger] = "Could not sign in. Error-BAD DATA"
    end

    redirect_to admin_dashboard_path
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

  private

  def find_user
    @user = User.find_by(email: request.env["omniauth.auth"].info.email)
  end
end

app/helpers/admin/currencies_helper.rb
module Admin::CurrenciesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend

  def delete_link(path, class_name = "")
    link_to '<i class="fas fa-trash " title="Delete"></i>'.html_safe,
            path,
            method: :delete,
            data: { confirm: "Are you sure?" },
            class: class_name
  end
end

app/views/admin/admin/dashboard.html.erb
<div class="mb-4 mt-2 clearfix">
  <h3 class="d-inline-block mb-0">Dashboard</h3>
</div>

app/views/admin/countries/_edit.html.erb
<%= render "form" %>

app/views/admin/countries/_form.html.erb
<div class="modal-header">
  <h5 class="modal-title" id="exampleModalCenterTitle">Add Country</h5>
  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

<%= form_for [:admin, @country], remote: true do |f| %>
  <div class="modal-body">
    <%= render partial: "layouts/form_errors", locals: { model: @country } %>

    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, required: true, class: "form-control", placeholder: "Country Name", autocomplete: :off, maxlength: 255 %>
    </div>

    <div class="form-group">
      <%= f.label :code %>
      <%= f.text_field :code, required: true, class: "form-control", maxlength: 2, pattern: "[A-Za-z]{2}", placeholder: "Country Code", autocomplete: :off %>
    </div>

    <div class="form-check">
      <%= f.check_box :active, class: "form-check-input" %>
      <%= f.label :active, class: "form-check-label ml-2" %>
    </div>
  </div>

  <div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-dismiss="modal" title="Close">Close</button>
    <%= f.submit class: "btn btn-primary", disabled_with: "Saving..." , title: "Save Country" %>
  </div>
<% end %>

app/views/admin/countries/_new.html.erb
<%= render "form" %>

app/views/admin/countries/edit.html.erb
<h1 class="text-center mb-5">Edit Country</h1>

<div class="row justify-content-center">
  <div class="col-4">
    <%= render "form" %>
  </div>
</div

app/views/admin/countries/edit.js.erb
$('#country_form_modal').find('.modal-content').html("<%= j (render 'edit') %>");
$('#country_form_modal').modal();

app/views/admin/countries/index.html.erb
<div class="mb-4 mt-2 clearfix">
  <h3 class="d-inline-block mb-0">Countries</h3>
  <%= link_to '<i class="fas fa-plus"></i> Add new country'.html_safe, new_admin_country_path, data: { remote: true, toggle: "modal", target: "#country_form_modal" }, class: "float-right btn btn-primary", title: "Add new country" %>
</div>

<div class="table-responsive country-list">
  <table class="table table-hover text-center">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Code</th>
        <th scope="col">Status</th>
        <th scope="col">Actions</th>
      </tr>
    </thead>

    <tbody>
      <% @countries.each.with_index(1) do |country, index| %>
        <tr>
          <th scope="row"><%= index %></th>
          <td><%= country.name %></td>
          <td><%= country.code %></td>
          <td><%= country.active ? '<i class="far fa-check-circle" title="Active"></i>'.html_safe : '<i class="far fa-times-circle" title="Deactive"></i>'.html_safe %></td>
          <td>
            <%= link_to '<i class="fas fa-pencil-alt"></i>'.html_safe, edit_admin_country_path(country), data: { remote: true, toggle: "modal", target: "#country_form_modal" }, class: "mr-2", title: "Edit" %>
            <%= delete_link admin_country_path(country), class_name="ml-2" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= render "layouts/pagy" %>

<!-- DIV for Bootstrap Modal -->
<div class="modal fade" id="country_form_modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <!-- bootstrap modal content goes here -->
    </div>
  </div>
</div>

app/views/admin/countries/new.html.erb
<h1 class="text-center mb-5">New Country</h1>

<div class="row justify-content-center">
  <div class="col-4">
    <%= render "form" %>
  </div>
</div

app/views/admin/countries/new.js.erb
$('#country_form_modal').find('.modal-content').html("<%= j (render 'edit') %>");
$('#country_form_modal').modal();

app/views/admin/currencies/_edit.html.erb
<%= render "form" %>

app/views/admin/currencies/_form.html.erb
<div class="modal-header">
  <h5 class="modal-title" id="exampleModalCenterTitle">Add Currency</h5>
  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

<%= form_for [:admin, @currency], remote: true do |f| %>
  <div class="modal-body">
    <%= render partial: "layouts/form_errors", locals: { model: @currency } %>

    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, required: true, class: "form-control", placeholder: "Currency Name", autocomplete: :off, maxlength: 255 %>
    </div>

    <div class="form-group">
      <%= f.label :code %>
      <%= f.text_field :code, required: true, class: "form-control", placeholder: "Currency Code", autocomplete: :off %>
    </div>

    <div class="form-group">
      <%= f.label :symbol %>
      <%= f.text_field :symbol, required: true, class: "form-control", maxlength: 1, placeholder: "Currency symbol", autocomplete: :off %>
    </div>

    <div class="form-check">
      <%= f.check_box :active, class: "form-check-input" %>
      <%= f.label :active, class: "form-check-label ml-2" %>
    </div>
  </div>

  <div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-dismiss="modal" title="Close">Close</button>
    <%= f.submit class: "btn btn-primary", disabled_with: "Saving..." , title: "Save Currency" %>
  </div>
<% end %>

app/views/admin/currencies/_new.html.erb
<%= render "form" %>

app/views/admin/currencies/edit.js.erb
$('#currency_form_modal').find('.modal-content').html("<%= j (render 'edit') %>");
$('#currency_form_modal').modal();

app/views/admin/currencies/index.html.erb
<div class="mb-4 mt-2 clearfix">
  <h3 class="d-inline-block mb-0">Currencies</h3>
  <%= link_to '<i class="fas fa-plus"></i> Add new currency'.html_safe, new_admin_currency_path, data: { remote: true, toggle: "modal", target: "#currency_form_modal" }, class: "float-right btn btn-primary", title: "Add new currency" %>
</div>

<div class="table-responsive currency-list">
  <table class="table table-hover text-center">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Code</th>
        <th scope="col">Symbol</th>
        <th scope="col">Status</th>
        <th scope="col">Actions</th>
      </tr>
    </thead>

    <tbody>
      <% @currencies.each.with_index(1) do |currency, index| %>
        <tr>
          <th scope="row"><%= index %></th>
          <td><%= currency.name %></td>
          <td><%= currency.code %></td>
          <td><%= currency.symbol %></td>
          <td><%= currency.active ? '<i class="far fa-check-circle" title="Active"></i>'.html_safe : '<i class="far fa-times-circle" title="Deactive"></i>'.html_safe %></td>
          <td>
            <%= link_to '<i class="fas fa-pencil-alt"></i>'.html_safe, edit_admin_currency_path(currency), data: { remote: true, toggle: "modal", target: "#currency_form_modal" }, class: "mr-2", title: "Edit" %>
            <%= delete_link admin_currency_path(currency), class_name="ml-2" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= render "layouts/pagy" %>

<!-- DIV for Bootstrap Modal -->
<div class="modal fade" id="currency_form_modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <!-- bootstrap modal content goes here -->
    </div>
  </div>
</div>

app/views/admin/currencies/new.js.erb
$('#currency_form_modal').find('.modal-content').html("<%= j (render 'edit') %>");
$('#currency_form_modal').modal();

app/views/home/index.html.erb
<div class="jumbotron">
  <h1 class="display-3">A Warm Welcome!</h1>
  <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsa, ipsam, eligendi, in quo sunt possimus non incidunt odit vero aliquid similique quaerat nam nobis illo aspernatur vitae fugiat numquam repellat.</p>
</div>

app/views/layouts/_alerts.html.erb
<% flash.each do |key, value|%>
  <div class="alert alert-<%= key %> alert-dismissible fade show m-3">
    <strong><%= value %></strong>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/layouts/_form_errors.html.erb
<% if model.errors.any? %>
  <div class="alert alert-danger" id="error_explaination">
    <% model.errors.full_messages.each.with_index(1) do |msg, index| %>
      <p class="text-danger">
        <%= index %>. <%= msg %>.
      </p>
    <% end %>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg">
    <button type="button" id="sidebar_collapse" class="btn btn-light">
      <i class="fas fa-align-left"></i>
    </button>
    <span class="ml-auto text-white"><%= current_user.first_name %></span>
</nav>

app/views/layouts/_pagy.html.erb
<div class="clearfix">
  <span class="float-right">
    <%= pagy_bootstrap_nav(@pagy).html_safe %>
  </span>
</div>

app/views/layouts/_sidebar.html.erb
<nav id="sidebar">
  <div class="sidebar-header">
    <h4>
      <%= link_to "Invoice Storage", admin_dashboard_path %>
    </h4>
  </div>

  <ul class="list-unstyled components">
    <li class="active">
      <a href="#home_submenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Master</a>
      <ul class="collapse list-unstyled" id="home_submenu">
        <li>
          <%= link_to "Countries", admin_countries_path, class: "nav-link" %>
          <%= link_to "Currencies", admin_currencies_path, class: "nav-link" %>
        </li>
      </ul>
    </li>
  </ul>
  <ul class="list-unstyled">
    <li><%= link_to "Sign out", logout_path, method: :delete %></li>
  </ul>
</nav>

app/views/layouts/_sign_in_modal.html.erb
<div class="modal fade" id="sign_in_modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-body">
        <%= link_to '<i class="fab fa-google"></i> Sign in with Google'.html_safe, login_path, class: "btn btn-danger btn-block btn-lg" %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Invoice Store</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= javascript_include_tag "//code.jquery.com/jquery-3.2.1.min.js" %>
  <%= javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" %>
  <%= javascript_include_tag "//stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" %>
  <%= stylesheet_link_tag "//stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
  <div class="wrapper">
    <%= render "layouts/sidebar" %>

    <div id="content">
      <%= render "layouts/navbar" %>
      <%= render "layouts/alerts" %>

      <div class="m-3">
        <%= yield %>
      </div>
    </div>
  </div>
</body>
</html>

app/views/layouts/home.html.erb
<html>
  <head>
    <title>Invoice Store</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_include_tag "//code.jquery.com/jquery-3.2.1.min.js" %>
    <%= javascript_include_tag "//stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" %>
    <%= stylesheet_link_tag "//stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header>
      <nav class="navbar navbar-expand-lg">
        <div class="sidebar-header text-white">
          <h4 class="m-0">
            <%= link_to "Invoice Storage", root_path %>
          </h4>
        </div>

        <% if current_user %>
          <%= link_to "Sign out", logout_path, method: :delete, class: "ml-auto text-white" %>
        <% else %>
          <a data-toggle="modal" class="ml-auto text-white" href="#sign_in_modal">Sign In</a>
        <% end %>
      </nav>
    </header>
    <main class="m-3">
      <%= render "layouts/alerts" %>
      <%= render "layouts/sign_in_modal" unless current_user %>
      <%= yield %>
    </main>
  </body>
</html>